JAVAFX_HOME ?= $(HOME)/.local/opt/javafx-sdk-21.0.4
PATH_TO_FX = $(JAVAFX_HOME)/lib
JAVAC_FLAGS = --module-path $(PATH_TO_FX) --add-modules javafx.controls,javafx.fxml
JAVA_FLAGS = --module-path $(PATH_TO_FX) --add-modules javafx.controls,javafx.fxml

SOURCES = $(wildcard *.java)
CLASSES = $(SOURCES:.java=.class)
MAIN_CLASS ?= HelloFX

all: $(CLASSES)

%.class: %.java
	javac $(JAVAC_FLAGS) $<

run: $(CLASSES)
	java $(JAVA_FLAGS) $(MAIN_CLASS)

clean:
	rm -f *.class

.PHONY: all run clean

